import sqlite3
import pandas as pd
import json
import os
from sqlalchemy import create_engine
from dotenv import load_dotenv
from langchain_core.tools import tool
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings

# Load env variables
load_dotenv()

# Paths
BASE_DIR = os.path.dirname(__file__)
LOCAL_DB_PATH = os.path.join(BASE_DIR, '..', 'data', 'enterprise_data.db')
INSIGHTS_PATH = os.path.join(BASE_DIR, '..', 'data', 'ml_insights.json')
VECTOR_DB_DIR = os.path.join(BASE_DIR, '..', 'data', 'vector_db')

def get_db_engine():
    """Returns the database engine based on environment configuration."""
    db_url = os.getenv('DATABASE_URL')
    if db_url and db_url.startswith('postgres'):
        if db_url.startswith('postgres://'):
            db_url = db_url.replace('postgres://', 'postgresql://', 1)
        return create_engine(db_url)
    else:
        return create_engine(f'sqlite:///{LOCAL_DB_PATH}')

@tool
def query_db(query: str) -> str:
    """Execute a SQL query against the enterprise customer database.
    
    The main table is 'customer_metrics'. 
    Columns: customerID, gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, 
    MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, 
    StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn.
    """
    try:
        engine = get_db_engine()
        df = pd.read_sql(query, engine)
        return df.to_json(orient='records')
    except Exception as e:
        return f"Error executing query: {str(e)}"

@tool
def get_ml_insights(query: str = "") -> str:
    """Retrieve the latest structured insights generated by the ML pipeline (churn risk, feature importance)."""
    try:
        if os.path.exists(INSIGHTS_PATH):
            with open(INSIGHTS_PATH, 'r') as f:
                return f.read()
        return "No ML insights available yet. Please run the ML pipeline."
    except Exception as e:
        return f"Error reading insights: {str(e)}"

def _run_drift_check() -> str:
    """
    Core drift-detection logic — called directly by the /drift endpoint
    and wrapped as a LangChain tool below.

    Compares two views against the saved training baseline:
      • Full dataset  — overall population (should be near-zero on static data)
      • Recent cohort — customers with tenure ≤ 6 months (often shows real shift
                        because new customers skew toward month-to-month / higher churn)

    Severity thresholds (applied to the max % deviation across tracked metrics):
      LOW    < 10 %
      MEDIUM  10 – 30 %
      HIGH   > 30 %
    """
    try:
        if not os.path.exists(INSIGHTS_PATH):
            return json.dumps({"error": "No baseline found. Run ml/churn_reasoning.py first."})

        with open(INSIGHTS_PATH) as f:
            insights = json.load(f)

        baseline = insights.get("drift_baseline")
        if not baseline:
            return json.dumps({"error": "No drift_baseline in insights. Re-run the ML pipeline."})

        engine = get_db_engine()

        # ── Full-dataset current stats ──────────────────────────────────────────
        full = pd.read_sql("""
            SELECT
                AVG(CAST(Churn AS FLOAT))  AS churn_rate,
                AVG(tenure)                AS avg_tenure,
                AVG(MonthlyCharges)        AS avg_monthly_charges,
                COUNT(*)                   AS total_records
            FROM customer_metrics
        """, engine).iloc[0]

        # ── Recent cohort (tenure ≤ 6 months) ──────────────────────────────────
        recent = pd.read_sql("""
            SELECT
                AVG(CAST(Churn AS FLOAT))  AS churn_rate,
                AVG(MonthlyCharges)        AS avg_monthly_charges,
                COUNT(*)                   AS cohort_size
            FROM customer_metrics
            WHERE tenure <= 6
        """, engine).iloc[0]

        def pct_diff(current, base):
            if not base:
                return 0.0
            return round(abs(float(current) - float(base)) / abs(float(base)) * 100, 2)

        def severity(max_pct):
            if max_pct >= 30:
                return "HIGH"
            if max_pct >= 10:
                return "MEDIUM"
            return "LOW"

        # ── Overall drift ───────────────────────────────────────────────────────
        overall_drifts = {
            "churn_rate":           pct_diff(full["churn_rate"],          baseline["churn_rate"]),
            "avg_tenure":           pct_diff(full["avg_tenure"],           baseline["avg_tenure"]),
            "avg_monthly_charges":  pct_diff(full["avg_monthly_charges"],  baseline["avg_monthly_charges"]),
        }
        overall_max   = max(overall_drifts.values())
        overall_sev   = severity(overall_max)

        # ── Recent cohort drift ─────────────────────────────────────────────────
        recent_drifts = {
            "churn_rate":           pct_diff(recent["churn_rate"],         baseline["churn_rate"]),
            "avg_monthly_charges":  pct_diff(recent["avg_monthly_charges"], baseline["avg_monthly_charges"]),
        }
        recent_max = max(recent_drifts.values())
        recent_sev = severity(recent_max)

        report = {
            "overall": {
                "severity":       overall_sev,
                "max_drift_pct":  overall_max,
                "metrics": {
                    "churn_rate": {
                        "baseline": baseline["churn_rate"],
                        "current":  round(float(full["churn_rate"]), 4),
                        "drift_pct": overall_drifts["churn_rate"],
                    },
                    "avg_tenure": {
                        "baseline": baseline["avg_tenure"],
                        "current":  round(float(full["avg_tenure"]), 2),
                        "drift_pct": overall_drifts["avg_tenure"],
                    },
                    "avg_monthly_charges": {
                        "baseline": baseline["avg_monthly_charges"],
                        "current":  round(float(full["avg_monthly_charges"]), 2),
                        "drift_pct": overall_drifts["avg_monthly_charges"],
                    },
                },
            },
            "recent_cohort": {
                "description":   "Customers with tenure ≤ 6 months vs training baseline",
                "cohort_size":   int(recent["cohort_size"]),
                "severity":      recent_sev,
                "max_drift_pct": recent_max,
                "metrics": {
                    "churn_rate": {
                        "baseline": baseline["churn_rate"],
                        "current":  round(float(recent["churn_rate"]), 4),
                        "drift_pct": recent_drifts["churn_rate"],
                    },
                    "avg_monthly_charges": {
                        "baseline": baseline["avg_monthly_charges"],
                        "current":  round(float(recent["avg_monthly_charges"]), 2),
                        "drift_pct": recent_drifts["avg_monthly_charges"],
                    },
                },
            },
            "recommendation": (
                "Retrain the model — significant distribution shift in recent customers."
                if recent_sev == "HIGH" else
                "Monitor closely — moderate drift detected in new customer cohort."
                if recent_sev == "MEDIUM" else
                "Model is stable. No retraining needed at this time."
            ),
        }
        return json.dumps(report, indent=2)

    except Exception as e:
        return json.dumps({"error": f"Drift check failed: {str(e)}"})


@tool
def check_data_drift(query: str = "") -> str:
    """
    Detect model/data drift by comparing the live customer database against the
    training-time baseline. Returns severity (LOW / MEDIUM / HIGH), per-metric
    drift percentages for both the full population and the recent customer cohort
    (tenure ≤ 6 months), and a retraining recommendation.

    Use this tool when asked about model health, data drift, retraining needs,
    or whether the ML model is still reliable.
    """
    return _run_drift_check()


@tool
def get_company_policy(query: str) -> str:
    """Search (RAG) for company policies related to a specific topic (e.g., 'pricing', 'retention') using the Vector Database.
    Always use this tool if the user asks about rules, pricing, or retention guidelines.
    """
    try:
        if not os.path.exists(VECTOR_DB_DIR):
            return "Vector database not found. Please run 'backend/ingest_knowledge.py' first."
        
        dir_contents = os.listdir(VECTOR_DB_DIR)
        if not dir_contents:
            return "Vector database is empty. Please run 'backend/ingest_knowledge.py' first."

        embedding_function = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
        vectorstore = Chroma(persist_directory=VECTOR_DB_DIR, embedding_function=embedding_function)
        
        results = vectorstore.similarity_search(query, k=2)
        if results:
            return "\n\n".join([doc.page_content for doc in results])
        else:
            return "No relevant policy documents found."
            
    except Exception as e:
        return f"Error searching policy documents: {str(e)}"
